
Applying domain randomization...
Traceback (most recent call last):
  File "udr_ole.py", line 98, in <module>
    main()
  File "udr_ole.py", line 92, in main
    train_test(args, train_env, test_env, w)
  File "udr_ole.py", line 65, in train_test
    model.learn(total_timesteps=2e3, reset_num_timesteps=True, callback=custom_callback, progress_bar=True)
NameError: name 'custom_callback' is not defined